# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import air_traffic_pb2 as air__traffic__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in air_traffic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AirTrafficServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAirTrafficInfo = channel.unary_unary(
                '/edu.itu.cs.atcas.infrastructure.ml.AirTrafficService/GetAirTrafficInfo',
                request_serializer=air__traffic__pb2.AirTrafficRequest.SerializeToString,
                response_deserializer=air__traffic__pb2.AirTrafficResponse.FromString,
                _registered_method=True)


class AirTrafficServiceServicer(object):
    """Service definition
    """

    def GetAirTrafficInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirTrafficServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAirTrafficInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirTrafficInfo,
                    request_deserializer=air__traffic__pb2.AirTrafficRequest.FromString,
                    response_serializer=air__traffic__pb2.AirTrafficResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edu.itu.cs.atcas.infrastructure.ml.AirTrafficService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edu.itu.cs.atcas.infrastructure.ml.AirTrafficService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AirTrafficService(object):
    """Service definition
    """

    @staticmethod
    def GetAirTrafficInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edu.itu.cs.atcas.infrastructure.ml.AirTrafficService/GetAirTrafficInfo',
            air__traffic__pb2.AirTrafficRequest.SerializeToString,
            air__traffic__pb2.AirTrafficResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
