# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: air_traffic.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ir_traffic.proto\x12\"edu.itu.cs.atcas.infrastructure.ml\"-\n\x11\x41irTrafficRequest\x12\x18\n\x10\x63onfiguration_id\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"\xfa\x01\n\x12\x41irTrafficResponse\x12\x18\n\x10\x63onfiguration_id\x18\x01 \x01(\t\x12\x1f\n\x17\x63ruising_sector_density\x18\x02 \x03(\x01\x12\x1f\n\x17\x63limbing_sector_density\x18\x03 \x03(\x01\x12!\n\x19\x64\x65scending_sector_density\x18\x04 \x03(\x01\x12\x1a\n\x12loss_of_separation\x18\x05 \x03(\x01\x12\x17\n\x0fspeed_deviation\x18\x06 \x03(\x01\x12\x14\n\x0csector_entry\x18\x07 \x03(\x01\x12\x1a\n\x12\x61irflow_complexity\x18\x08 \x03(\x01\"\xfc\x01\n\x14\x41irTrafficComplexity\x12\x18\n\x10\x63onfiguration_id\x18\x01 \x01(\t\x12\x1f\n\x17\x63ruising_sector_density\x18\x02 \x03(\x01\x12\x1f\n\x17\x63limbing_sector_density\x18\x03 \x03(\x01\x12!\n\x19\x64\x65scending_sector_density\x18\x04 \x03(\x01\x12\x1a\n\x12loss_of_separation\x18\x05 \x03(\x01\x12\x17\n\x0fspeed_deviation\x18\x06 \x03(\x01\x12\x14\n\x0csector_entry\x18\x07 \x03(\x01\x12\x1a\n\x12\x61irflow_complexity\x18\x08 \x03(\x01\x32\x9f\x02\n\x11\x41irTrafficService\x12\x82\x01\n\x11GetAirTrafficInfo\x12\x35.edu.itu.cs.atcas.infrastructure.ml.AirTrafficRequest\x1a\x36.edu.itu.cs.atcas.infrastructure.ml.AirTrafficResponse\x12\x84\x01\n\x14StreamAirTrafficInfo\x12\x30.edu.itu.cs.atcas.infrastructure.ml.EmptyRequest\x1a\x38.edu.itu.cs.atcas.infrastructure.ml.AirTrafficComplexity0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'air_traffic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRTRAFFICREQUEST']._serialized_start=57
  _globals['_AIRTRAFFICREQUEST']._serialized_end=102
  _globals['_EMPTYREQUEST']._serialized_start=104
  _globals['_EMPTYREQUEST']._serialized_end=118
  _globals['_AIRTRAFFICRESPONSE']._serialized_start=121
  _globals['_AIRTRAFFICRESPONSE']._serialized_end=371
  _globals['_AIRTRAFFICCOMPLEXITY']._serialized_start=374
  _globals['_AIRTRAFFICCOMPLEXITY']._serialized_end=626
  _globals['_AIRTRAFFICSERVICE']._serialized_start=629
  _globals['_AIRTRAFFICSERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
